## numpy
numpy其实就是一个多维的数组对象  
每一个np的数组都有一个shape和一个叫做dtype的方法

In [1]:
import numpy as np

In [2]:
data = [1,2,3,4,5]
n = np.array(data * 10)
print(data)
print(n)

[1, 2, 3, 4, 5]
[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2
 3 4 5 1 2 3 4 5 1 2 3 4 5]


### 1.嵌套序列

In [3]:
arr = [[1,2,3,4],[1,2,3,4]]
arr2 = np.array(arr)
print(arr2)
print(arr2.ndim)
print(arr2.shape)

[[1 2 3 4]
 [1 2 3 4]]
2
(2, 4)


In [5]:
np.arange(10)
# arange是range函数的数组版本

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2.矢量化

两个np数组相加，也就是对应位置的数据相加  
同理，适用其余运算

### 3.索引和切片

In [9]:
arr = np.arange(10)
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [10]:
arr_copy = arr.copy()
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 4.轴变换

In [12]:
arr = np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
arr.transpose((1,2,0))

array([[[ 0, 12],
        [ 1, 13],
        [ 2, 14],
        [ 3, 15]],

       [[ 4, 16],
        [ 5, 17],
        [ 6, 18],
        [ 7, 19]],

       [[ 8, 20],
        [ 9, 21],
        [10, 22],
        [11, 23]]])

### 5. 条件逻辑转数组
np.where等同于x if condition else y 矢量化的一个版本

In [15]:
x_arr = np.array([1.1,1.2,1.3])
y_arr = np.array([2.1,2.2,2.3])
condition = np.array([1,0,1])
result = [(x if c else y)for x,y,c in zip(x_arr, y_arr, condition)]
# zip接受的参数就是可迭代的对象
# zip（）函数用于将可迭代的对象作为参数，将对象中对应的元素打包成一个个元组，然后返回由这些元祖组成的列表
print(result)

[1.1, 2.2, 1.3]


In [17]:
r = np.where(condition, x_arr, y_arr)
r

array([1.1, 2.2, 1.3])

In [18]:
# 值替换
arr = np.random.randn(4,4)
print(arr)
arr_1 = np.where(arr>0, 2, -2)
print(arr_1)

[[ 0.86259118 -1.03210338 -0.38480025 -0.18323463]
 [ 0.62225565  0.07552586  0.093477   -0.75604673]
 [-2.1589589   0.4311525   1.20376223  0.77711661]
 [-0.60968089 -0.69644265 -0.59428926  0.35509973]]
[[ 2 -2 -2 -2]
 [ 2  2  2 -2]
 [-2  2  2  2]
 [-2 -2 -2  2]]
